from os.path import join

ENERGIA_ENTRENAMIENTO = 8
MIN_AUMENTO_EXPERIENCIA = 10
MAX_AUMENTO_EXPERIENCIA = 25
MIN_AUMENTO_ENTRENAMIENTO = 5
MAX_AUMENTO_ENTRENAMIENTO = 20
AUMENTAR_VIDA_PLANTA = 18
AUMENTAR_ATAQUE_FUEGO = 24
AUMENTAR_VELOCIDAD_AGUA = 28
GASTO_ENERGIA_BAYA = 7
PROB_EXITO_BAYA = 0.6
GASTO_ENERGIA_POCION = 10
PROB_EXITO_POCION = 0.7
AUMENTO_DEFENSA = 12
GASTO_ENERGIA_CARAMELO = 15
PROB_EXITO_CARAMELO = 0.8

RUTA_ENTRENADORES = join('entrenadores.csv')
RUTA_PROGRAMONES = join('programones.csv')
RUTA_OBJETOS = join('objetos.csv')
RUTA_RONDAS = join('guardar_ronda.txt')

